import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { GraphQLClient } from 'graphql-request';
import MainPosts from '../components/MainPosts';

export default function Home({ posts }) {
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Blog Next App</title>
          <meta name='description' content='Generated by create next app' />

          <link rel='icon' href='/favicon.ico' />
        </Head>

        <div>
          <MainPosts posts={posts} />
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const graphcms = new GraphQLClient(
    'https://api-ap-southeast-2.graphcms.com/v2/cl29xmlz11iqj01ywas0g1j7m/master'
  );

  const { posts } = await graphcms.request(
    `
    query MyQuery {
      posts(orderBy: updatedAt_DESC) {
        id
        author {
          id
          name
          photo {
            url
          }
        }
        slug
        title
        headline
        updatedAt
      }
    }
    `
  );

  return {
    props: {
      posts,
    },
  };
}
